import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Common Issues — Agent Team OS Guide',
}

const content = `<div class="breadcrumbs">
          <a href="/">Home</a> / Troubleshooting
        </div>

        <h1>Common Issues</h1>
        <p>A quick reference for the most frequently encountered problems and how to fix them. If your issue isn't listed here, check the <a href="/troubleshooting/faq">FAQ</a> or ask Forge for a system health check.</p>

        <div class="callout note">
          <strong>When in doubt, ask Forge to run a system health check.</strong> Forge can diagnose most issues automatically and will report back with specific findings and recommended fixes.
        </div>

        <h3>"I didn't get my morning report"</h3>
        <p>The morning report is generated by Forge and delivered via Pushover. If it didn't arrive, work through these checks:</p>
        <ul>
          <li><strong>Check Pushover configuration.</strong> Verify that your Pushover user key and application token are correctly set in the agent configuration. Open the Pushover app on your phone and confirm notifications are enabled.</li>
          <li><strong>Check that cron jobs are running.</strong> SSH into the EC2 instance and run <code>crontab -l</code> to confirm the morning report job is scheduled. Look for the entry that triggers the report generation script.</li>
          <li><strong>Check Forge logs.</strong> Review the Forge logs for the time the report should have been generated. Look for errors related to data gathering, report formatting, or notification delivery.</li>
        </ul>

        <h3>"My LogSeq data seems out of date"</h3>
        <p>If the data in LogSeq looks stale or doesn't reflect recent changes, the issue is almost certainly with Syncthing.</p>
        <ul>
          <li><strong>Syncthing might be paused or disconnected.</strong> Check whether Syncthing is running on both your local machine and the EC2 instance. A network disruption or Tailscale disconnect can cause sync to stall.</li>
          <li><strong>Check the Syncthing Web UI.</strong> Open <code>http://localhost:8384</code> in your browser to see the current sync status. Look for any folders marked as "Paused" or devices listed as "Disconnected."</li>
          <li><strong>See the dedicated Syncthing page.</strong> For deeper diagnosis, head to the <a href="/troubleshooting/syncthing">Syncthing Troubleshooting</a> page for detailed steps.</li>
        </ul>

        <h3>"An agent did something I didn't expect"</h3>
        <p>If an agent took an action you didn't authorize or didn't anticipate, don't panic. Here's how to investigate and prevent it from happening again.</p>
        <ul>
          <li><strong>Check the trust decision log.</strong> Run <code>trust-system.sh log 50</code> to see recent trust decisions. Every check, approval, and denial is logged with timestamps, agent names, actions, and outcomes. This tells you exactly what happened and whether the trust system allowed or blocked the action.</li>
          <li><strong>Review the agent's trust level.</strong> Run <code>trust-system.sh get-level &lt;agent&gt;</code> to see where the agent currently sits. If the action exceeded what you're comfortable with, the trust level may be too high.</li>
          <li><strong>Demote the agent if needed.</strong> Run <code>trust-system.sh demote &lt;agent&gt; &lt;new-level&gt; &lt;reason&gt;</code> to immediately lower the agent's trust level. This takes effect right away — the agent will need approval for more actions going forward.</li>
          <li><strong>Check for pending approvals.</strong> Run <code>trust-system.sh list-pending</code> to see if the agent has other actions waiting for your review.</li>
          <li><strong>Review full system status.</strong> Run <code>trust-system.sh status</code> for an overview of all agent levels, pending approvals, and recent decisions.</li>
        </ul>
        <p>See the <a href="/reference/commands#trust-system">Trust System Commands</a> reference for the complete CLI, and <a href="/agents/trust-levels">Trust Levels</a> for how the permission system works.</p>

        <h3>"I can't connect to the EC2 instance"</h3>
        <p>The EC2 instance is accessed over Tailscale, so connectivity issues usually trace back to the VPN layer or SSH configuration.</p>
        <ul>
          <li><strong>Verify Tailscale is running.</strong> Run <code>tailscale status</code> on your local machine. You should see the EC2 instance listed as a connected peer. If Tailscale isn't running, start it first.</li>
          <li><strong>Check your SSH key.</strong> Make sure your SSH key is loaded (<code>ssh-add -l</code>) and that the corresponding public key is on the EC2 instance. If you recently rotated keys, the remote authorized_keys file may need updating.</li>
          <li><strong>Try <code>tailscale status</code> on the EC2 side.</strong> If you can reach the instance through the AWS console, check Tailscale from there as well. The instance may have lost its Tailscale connection due to a restart or network change.</li>
        </ul>

        <h3>"Cron jobs aren't running"</h3>
        <p>Cron jobs power the automated cadence (morning reports, backups, etc.). If they stop, the whole rhythm breaks down.</p>
        <ul>
          <li><strong>Check if a crontab exists.</strong> Run <code>crontab -l</code> on the EC2 instance. If the output is empty or shows "no crontab for user," the jobs need to be reinstalled. See <a href="/automation/cron-jobs">Cron Jobs</a> for the expected entries.</li>
          <li><strong>Verify the EC2 instance is running.</strong> Log into the AWS console and confirm the instance state is "running." If it was stopped (manually or due to a billing issue), cron jobs will not execute.</li>
          <li><strong>Check system logs.</strong> Review <code>/var/log/syslog</code> or use <code>journalctl -u cron</code> to see if cron itself is running and whether any jobs failed. Look for permission errors or missing script paths.</li>
        </ul>

        <div class="action-section">
          <h2>What You Do Next</h2>
          <ul>
            <li>If your issue involves Syncthing, visit the <a href="/troubleshooting/syncthing">Syncthing Troubleshooting</a> page for deeper guidance.</li>
            <li>For general questions about the system, check the <a href="/troubleshooting/faq">FAQ</a>.</li>
            <li>Ask Forge to run a health check if you're unsure where the problem lies.</li>
            <li>If the problem persists, review the <a href="/reference/file-locations">File Locations</a> reference to find relevant log files.</li>
          </ul>
        </div>`

export default function Page() {
  return <div dangerouslySetInnerHTML={{ __html: content }} />
}
